fixed https://github.com/qiskit-community/qiskit-textbook/issues/1578
Qiskit/textbook pull request #18
Opened 2023-04-25 19:51 UTC by HannesGitH

one minor part isn't rendered as mathjax but as plaintext, see https://github.com/qiskit-community/qiskit-textbook/issues/1578

i fixed that in notebooks/ch-algorithms/quantum-counting.ipynb

---

the first two commits and other files are independent but i also formatted the readme (removed md violations) and made the correct tensorflow dependencies for macos in requirements.txt available

2023-04-25 19:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/textbook?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/textbook?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/textbook?pullRequest=18) it.</sub>

2023-04-27 12:37 UTC, frankharkins requested changes
Thanks, can you reset the changes to `README.md` and `requirements.txt` please?

2023-04-28 12:27 UTC, HannesGitH commented
> Thanks, can you reset the changes to `README.md` and `requirements.txt` please?

done ✅
---
though i think they could be addressed as well, at least making the requirements also install on macos

2023-05-04 19:07 UTC, frankharkins approved these changes
Thank you!

2023-05-04 19:07 UTC, merged